### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by walter211** [zouzg/mybatis-generator-gui#230]
Exception in thread "JavaFX Application Thread" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at com.zzg.mybatis.generator.MainUI.<clinit>(MainUI.java:22)
        at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplicationWithArgs$157(LauncherImpl.java:352)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$176(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$174(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$175(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 9 more

**Comment by bfchengnuo** [comment]
解压 zip 后进入文件夹运行 jar，不要只把 jar 包解压出来运行；
祝好运 :)

**Comment by zouzg** [comment]
对的，按照上面兄台的意见可运行。
